name: mi_card
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/atishay.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3.ttf
